erDiagram
    AGG_LOAN_TXN_ACM_MTH {
        Date	TXN_DATE PK
        VARCHAR2(50 )	ARRANGEMENT_NBR PK
        VARCHAR2(3 )	CURRENCY_CODE
        VARCHAR2(50 )	CATE_CODE
        VARCHAR2(50 )	SUB_PRODUCT_CODE
        VARCHAR2(50 )	SECTOR_CODE
        VARCHAR2(50 )	LOAN_INDUSTRY_CODE
        VARCHAR2(50 )	T24_CUST_ID
        VARCHAR2(50 )	PARTY_KEY
        VARCHAR2(50 )	BRANCH_CODE FK
        VARCHAR2(50 )	COA_CODE
        VARCHAR2(50 )	TERM
        NUMBER(38,6)	ARRANGEMENT_INT_RATE
        VARCHAR2 (255 )	INT_KEY
        VARCHAR2(50 )	CAMPAIGN_CODE
        VARCHAR2(50 )	CUST_CREDIT_RATING
        VARCHAR2(50 )	DIVISION_CODE
        VARCHAR2 (50 )	LEGACY_CONTRACT_ID
        VARCHAR2 (50 )	LOAN_PURPOSE_CODE
        VARCHAR2 (50 )	PRODUCT_CODE
        VARCHAR2 (50 )	ARRANGEMENT_CREDIT_RATING
        VARCHAR2 (50 )	FUND_SOURCE_CODE
        VARCHAR2 (50 )	SECURED_LOAN_IND
        NUMBER	DISBURSE_MTD_LCY_AMT
        NUMBER	PAYMENT_MTD_LCY_AMT
        NUMBER	DISBURSE_YTD_LCY_AMT
        NUMBER	PAYMENT_YTD_LCY_AMT
        Varchar(50 char)	LAST_UPDATED_BY
        DATE	LAST_UPDATE_DATE
        DATE	VALUE_DATE
        DATE	MATURITY_DATE
        VARCHAR2(200)	CIC_PURPOSE_CODE
        VARCHAR2(200)	SME_CUST_IND
        VARCHAR2(200)	CRA_APNT_CODE
        VARCHAR2(200)	T24_LINE
        VARCHAR2(200)	MTH_TXN_IND
        VARCHAR2 (4000 )	LOAN_PURPOSE_DESC
        Number	DISBURSE_MTD_FCY_AMT
        Number	PAYMENT_MTD_FCY_AMT
        Number	DISBURSE_YTD_FCY_AMT
        Number	PAYMENT_YTD_FCY_AMT
    }

    SMY_LOAN_BAL_MTH {
        DATE  TXN_DATE	PK, FK
        NUMBER(10)	BATCH_VERSION_ID PK, FK
        VARCHAR2(50 )	ARRANGEMENT_KEY PK
        VARCHAR2(50 )	ARRANGEMENT_NBR PK
        VARCHAR2(50 )	PARTY_KEY 
        VARCHAR2(50 )	T24_CUST_ID
        VARCHAR2(250 )	PARTY_FULL_NAME
        VARCHAR2(50 )	BRANCH_CODE  FK
        VARCHAR2(250 )	BRANCH_NAME
        VARCHAR2(50 )	PRODUCT_CODE
        VARCHAR2(250 )	PRODUCT_NAME
        VARCHAR2(50 )	SECTOR_CODE
        VARCHAR2(250 )	SECTOR_NAME
        VARCHAR2(50 )	LOAN_INDUSTRY_CODE
        VARCHAR2(4000)	LOAN_PURPOSE
        VARCHAR2(50 )	CUS_DIVISION_CODE
        VARCHAR2(50 )	DIVISION_CODE
        DATE	VALUE_DATE
        DATE	MATURITY_DATE
        VARCHAR2(50 )	COA_CODE
        VARCHAR2(3 )	CURRENCY_CODE
        NUMBER(38,6)	EXCHANGE_RATE
        NUMBER(15,9)	INT_RATE
        VARCHAR2 (50 )	CATE_CODE
        VARCHAR2 (50 )	SUB_PRODUCT_CODE
        NUMBER(38,6)	FCY_AMT
        NUMBER(38,6)	LCY_AMT
        VARCHAR2(50 )	CUST_CREDIT_RATING
        VARCHAR2(50 )	ARRANGEMENT_CREDIT_RATING
        VARCHAR2(50 )	FUND_SOURCE_CODE
        VARCHAR2(50 )	LEGACY_CONTRACT_ID
        VARCHAR2(50 )	TERM
        VARCHAR2(50 )	TERM_TYPE
        VARCHAR2(50 )	CIC_PURPOSE_CODE
        VARCHAR2(50 )	LIMIT_CODE
        NUMBER(38,6)	ORIG_PNP_AMT
        VARCHAR2(50 )	BRANCH_CODE_MAP_TT35
        VARCHAR2(50 )	SECTOR_CODE_TT35
        VARCHAR2(50 )	USE_OF_LOAN_CODE_TT35
        VARCHAR2(50 )	CIC_PURPOSE_CODE_MAP
        VARCHAR2(50 )	DIVISION_CODE_TT31
        DATE	LAST_UPDATED_DATE
        VARCHAR2(250 )	LAST_UPDATED_BY
        VARCHAR2(50 )	SME_CUST_IND
        VARCHAR2(50 )	PROJECT_CODE
        VARCHAR2(50 )	CAMPAIGN_CODE
        VARCHAR2 (255 )	INT_KEY
        VARCHAR2 (255 )	DOUBTFUL_STATUS
        VARCHAR2(50 )	DLGN_PARTY_KEY
        VARCHAR2(50 )	SECURED_LOAN_IND
        DATE	NXT_INT_RATE_CHANGE_DATE
    }

    SMY_BRANCH_MTH {
        DATE	TXN_DATE PK
        VARCHAR2(50 )	BRANCH_CODE PK
        VARCHAR2(50 )	W4_BRANCH_CODE
        VARCHAR2(50 )	T24_PARENT_BRANCH_SBV_CODE
        VARCHAR2(50 )	GL_PARENT_BRANCH_MB_CODE
        VARCHAR2(50 )	GL_PARENT_BRANCH_SBV_CODE
        VARCHAR2(50 )	T24_PARENT_BRANCH_MB_CODE
        VARCHAR2(250 )	BRANCH_NAME
        VARCHAR2(250 )	MNEMONIC
        VARCHAR2(50 )	BRANCH_SWIFT_CODE
        VARCHAR2(50 )	BRANCH_CITAD_CODE
        VARCHAR2(50 )	BRANCH_CIC_CODE
        VARCHAR2(250 )	BRANCH_TAX_NBR
        VARCHAR2(250 )	BRANCH_PHONE_NBR
        VARCHAR2(50 )	BRANCH_TYPE
        VARCHAR2(250 )	BRANCH_STREET
        VARCHAR2(250 )	BRANCH_WARD
        VARCHAR2(250 )	BRANCH_DISTRICT
        VARCHAR2(250 )	BRANCH_PROVINCE
        VARCHAR2(250 )	BRANCH_COUNTRY
        VARCHAR2(50 ) BRANCH_AREA_CODE
        VARCHAR2(50 )	BRANCH_REGION_CODE
        VARCHAR2(50 )	BRANCH_SUB_REGION_CODE
        DATE	BRANCH_FROM_DATE
        DATE	BRANCH_TO_DATE
        DATE	LAST_UPDATED_BY
        VARCHAR2(250 )	LAST_UPDATE_DATE
    }  
    SMY_BRANCH_MTH ||--o{ SMY_LOAN_BAL_MTH : "BRANCH_CODE, TXN_DATE"
    SMY_BRANCH_MTH ||--o{ AGG_LOAN_TXN_ACM_MTH : "BRANCH_CODE, TXN_DATE"
    SMY_LOAN_BAL_MTH ||--o{ AGG_LOAN_TXN_ACM_MTH : "ARRANGEMENT_NBR, TXN_DATE"
