version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_HOST: db
    ports:
      - "4000:80"
    depends_on:
      - db
    volumes:
      - ./frontend:/app/frontend
      - ./bank.xlsx:/app/bank.xlsx
      - ./env.py:/app/env.py
      - ./diagram.mmd:/app/diagram.mmd

volumes:
  postgres_data: